train_dataset:
  name: dataset.data_val.PolypObjDataset
  params:
    image_root: '/opt/data/private/jyp/data/polyp/TrainDataset/image/'
    gt_root: '/opt/data/private/jyp/data/polyp/TrainDataset/mask/'
    trainsize: 256

test_dataset:
  COD10K:
    name: dataset.data_val.test_dataset
    params:
      image_root: '/opt/data/private/jyp/data/polyp/ValDataset/images/'
      gt_root: '/opt/data/private/jyp/data/polyp/ValDataset/masks/'
      testsize: 256
  POLYP:
    name: dataset.data_val.test_dataset
    params:
      image_root: '/opt/data/private/jyp/data/polyp/TestDataset/CVC-300/images/'
      gt_root: '/opt/data/private/jyp/data/polyp/TestDataset/CVC-300/masks/'
      testsize: 256
  CHAMELEON:
    name: dataset.data_val.test_dataset
    params:
      image_root: '/opt/data/private/jyp/data/polyp/TestDataset/Kvasir/images/'
      gt_root: '/opt/data/private/jyp/data/polyp/TestDataset/Kvasir/masks/'
      testsize: 256
  NC4K:
    name: dataset.data_val.test_dataset
    params:
      image_root: '/media/datatset/COD10K/TestDataset/NC4K/Imgs/'
      gt_root: '/media/datatset/COD10K/TestDataset/NC4K/GT/'
      testsize: 256
  CDS2K:
    name: dataset.cds2k_dataset.cds2K_dataset
    params:
      root: '/media/datatset/CDS2K'
      testsize: 256
