train_dataset:
  name: dataset.data_val.PolypObjDataset
  params:
    image_root: '/TrainDataset/image/'
    gt_root: '/TrainDataset/mask/'
    trainsize: 256

test_dataset:
  COD10K:
    name: dataset.data_val.test_dataset
    params:
      image_root: ''
      gt_root: ''
      testsize: 256
  POLYP:
    name: dataset.data_val.test_dataset
    params:
      image_root: '/polyp/TestDataset/CVC-300/images/'
      gt_root: '/TestDataset/CVC-300/masks/'
      testsize: 256
  CHAMELEON:
    name: dataset.data_val.test_dataset
    params:
      image_root: ''
      gt_root: ''
      testsize: 256
  NC4K:
    name: dataset.data_val.test_dataset
    params:
      image_root: ''
      gt_root: ''
      testsize: 256
  CDS2K:
    name: dataset.cds2k_dataset.cds2K_dataset
    params:
      root: '/media/datatset/CDS2K'
      testsize: 256
